apiVersion: v1
kind: Service
metadata:
  name: booking-service
  namespace: movie-booking
spec:
  selector:
    app: booking-service
    version: blue   # ðŸ‘ˆ switch to green during deployment
  ports:
    - port: 80
      targetPort: 9091
