server:
  port: 9093

spring:
  application:
    name: inventory-service

  data:
    redis:
      host: booking-redis
      port: 6379
      timeout: 2000

  kafka:
    bootstrap-servers: booking-kafka:9094
    consumer:
      group-id: inventory-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"